apiVersion: apps/v1
kind: Deployment
metadata: 
  name: webapp
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      #nodeSelector:
        #"kubernetes.io/os: linux"
      containers:
      - name: webapp
        image: reproacr.azurecr.io/comments-demo/comments-webapp:latest #need the proper azure image registry
        ports:
        - containerPort: 7020
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 7020
    targetPort: 7020
  selector:
    app: webapp
---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: mongo
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels: 
      app: mongo
  template:
    metadata: 
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: reproacr.azurecr.io/comments-demo/mongo:latest
        ports:
        - containerPort: 27017
          name: mongo
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  ports:
  - port: 27017
  selector:
    app: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  ports:
  - port: 80
    targetPort: 7020
  selector:
    app: webapp
  type: LoadBalancer  