#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.
# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app
    
# Copy csproj and restore as distinct layers
COPY ./*.csproj ./
# COPY ./ProjectName.sln ./
RUN dotnet restore ./
    
# Copy everything else and build
COPY ./ ./
RUN dotnet publish -c Release -o out
    
# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out .

EXPOSE 7020

# ENTRYPOINT ["dotnet", "ProjectExe.dll"]
CMD dotnet CommentWebAPI.dll --urls=http://0.0.0.0:7020